/**
 * Encrypted message channel for P2P chat (V2 encryption).
 *
 * Every protocol line after the handshake is encrypted with AES-256-GCM using a
 * session key derived from the shared password:
 *
 *   key = scrypt(password, salt, 32)
 *
 * The salt is random per session, generated by the listener (Ripster) and sent
 * to the connector in a single plaintext `hello` line when the socket opens.
 * A peer with the wrong password derives a different key, so nothing it sends
 * can be decrypted (GCM authentication fails) and nothing it receives is
 * readable — including all chat content and file chunks.
 *
 * Wire format (one message per line, newline-framed like the V1 protocol):
 *   E1.<base64 iv>.<base64 auth tag>.<base64 ciphertext>\n
 *
 * Only two plaintext line types are ever allowed:
 *   - `hello` (server -> client): carries the session salt, no secrets
 *   - `auth-failed` (server -> client): tells a wrong-password client why it
 *     was rejected (it could not decrypt this message otherwise)
 */
import { randomBytes, scryptSync, createCipheriv, createDecipheriv } from 'crypto'
import { ProtocolMessage } from './protocol'

const WIRE_PREFIX = 'E1.'
const KEY_LENGTH = 32 // AES-256
const IV_LENGTH = 12 // GCM standard nonce size
const SALT_LENGTH = 16

/** Generate a random per-session salt (hex) for key derivation. */
export function generateSalt(): string {
  return randomBytes(SALT_LENGTH).toString('hex')
}

/** Derive the AES-256 session key from the shared password and session salt. */
export function deriveKey(password: string, saltHex: string): Buffer {
  return scryptSync(password, Buffer.from(saltHex, 'hex'), KEY_LENGTH)
}

/** True if a wire line is an encrypted frame (vs. a plaintext handshake line). */
export function isEncryptedLine(line: string): boolean {
  return line.startsWith(WIRE_PREFIX)
}

/** Encrypt a protocol message into a newline-terminated wire line. */
export function encryptMessage(key: Buffer, msg: ProtocolMessage): string {
  const iv = randomBytes(IV_LENGTH)
  const cipher = createCipheriv('aes-256-gcm', key, iv)
  const plaintext = Buffer.from(JSON.stringify(msg), 'utf8')
  const ciphertext = Buffer.concat([cipher.update(plaintext), cipher.final()])
  const tag = cipher.getAuthTag()
  return `${WIRE_PREFIX}${iv.toString('base64')}.${tag.toString('base64')}.${ciphertext.toString('base64')}\n`
}

/**
 * Decrypt a wire line. Returns null when the line is malformed or fails GCM
 * authentication (wrong key — i.e. wrong password — or tampered data).
 */
export function decryptMessage(key: Buffer, line: string): ProtocolMessage | null {
  try {
    if (!isEncryptedLine(line)) return null
    const parts = line.trim().slice(WIRE_PREFIX.length).split('.')
    if (parts.length !== 3) return null
    const iv = Buffer.from(parts[0], 'base64')
    const tag = Buffer.from(parts[1], 'base64')
    const ciphertext = Buffer.from(parts[2], 'base64')
    if (iv.length !== IV_LENGTH || tag.length !== 16) return null
    const decipher = createDecipheriv('aes-256-gcm', key, iv)
    decipher.setAuthTag(tag)
    const plaintext = Buffer.concat([decipher.update(ciphertext), decipher.final()])
    return JSON.parse(plaintext.toString('utf8'))
  } catch (_err) {
    // Wrong key, corrupted frame, or tampering — never throw to the socket loop
    return null
  }
}
